apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-crd-prod
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: yany-apps
  
  source:
    repoURL: https://github.com/yany-ops/argocd-apps.git
    targetRevision: HEAD
    path: charts/istio/base
    helm:
      releaseName: istio-crd
      valuesObject: {}
  
  destination:
    server: https://prod.cluster.yanychoi.com:6443
    namespace: istio-system
  
  syncPolicy:
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-prod
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: yany-apps
  
  source:
    repoURL: https://github.com/yany-ops/argocd-apps.git
    targetRevision: HEAD
    path: charts/istio/istiod
    helm:
      releaseName: istiod
      valuesObject: {}
  
  destination:
    server: https://prod.cluster.yanychoi.com:6443
    namespace: istio-system
  
  syncPolicy:
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway-prod
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: yany-apps
  
  source:
    repoURL: https://github.com/yany-ops/argocd-apps.git
    targetRevision: HEAD
    path: charts/istio/gateway
    helm:
      releaseName: istio-ingressgateway
      valuesObject:
        service:
          type: NodePort
          ports:
          - name: status-port
            nodePort: 30021
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http2
            nodePort: 30080
            port: 80
            protocol: TCP
            targetPort: 80
          - name: https
            nodePort: 30443
            port: 443
            protocol: TCP
            targetPort: 443
  
  destination:
    server: https://prod.cluster.yanychoi.com:6443
    namespace: istio-system
  
  syncPolicy:
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-egressgateway-prod
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: yany-apps
  
  source:
    repoURL: https://github.com/yany-ops/argocd-apps.git
    targetRevision: HEAD
    path: charts/istio/gateway
    helm:
      releaseName: istio-egressgateway
      valuesObject:
        service:
          type: ClusterIP
  
  destination:
    server: https://prod.cluster.yanychoi.com:6443
    namespace: istio-system
  
  syncPolicy:
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=false