apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cilium
  repo: https://helm.cilium.io
  releaseName: cilium
  namespace: kube-system
  version: 1.15.9
  valuesFile: values.yaml

resources:
- ip-pool.yaml
- l2-policy.yaml