apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-prod
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: yany-apps
  
  source:
    repoURL: https://github.com/yany-ops/argocd-apps.git
    targetRevision: HEAD
    path: charts/cert-manager
    helm:
      valuesObject:
        installCRDs: true
  
  destination:
    server: https://prod.cluster.yanychoi.com:6443
    namespace: cert-manager
  
  syncPolicy:
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true