apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: prometheus
  namespace: prometheus
  version: 27.13.0
  valuesFile: values.yaml
