apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "service-endpoint.fullname" . }}-cert
  namespace: istio-system # istio 설치경로
spec:
  secretName: {{ include "service-endpoint.fullname" . }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.domain }}
  dnsNames:
  - {{ .Values.domain }}
