kind: Gateway
apiVersion: networking.istio.io/v1beta1
metadata:
  name: {{ include "service-endpoint.fullname" . }}-ingress-gw
spec:
  servers:
    - hosts:
        - {{ .Values.domain }}
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: {{ include "service-endpoint.fullname" . }}-tls
        mode: SIMPLE
    - hosts:
        - {{ .Values.domain }}
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    app: istio-ingressgateway
