apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  releaseName: argo-cd
  namespace: argo-cd
  version: 7.9.1
  valuesFile: values.yaml
