apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql
  data:
  - secretKey: password
    remoteRef:
      key: mysql
      property: password
