apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer-ops
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: yany-apps
  
  source:
    repoURL: https://github.com/yany-ops/argocd-apps.git
    targetRevision: HEAD
    path: charts/cluster-issuer
  
  destination:
    server: https://kubernetes.default.svc