apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: endpoints-ops
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: yany-apps
  
  source:
    repoURL: https://github.com/yany-ops/argocd-apps.git
    targetRevision: HEAD
    path: apps/ops/endpoints
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: default
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true